const express=require('express'); const router=express.Router(); const {pool}=require('../config/database'); const {id,now,publicUser,isAdmin}=require('../utils'); const {auth}=require('../middleware/auth');
const MAP={
 ActivityLog:{table:'activity_logs',fields:['id','created_date','updated_date','user_email','user_name','action','entity_type','entity_id','details']},
 Booking:{table:'bookings',fields:['id','created_date','updated_date','booking_reference','package_id','package_name','tour_type','booking_date','guest_count','customer_name','customer_email','customer_phone','special_requests','total_amount','reservation_fee_amount','payment_type','payment_amount_due','payment_mode','payment_qr_code_id','payment_qr_code_label','receipt_url','status','payment_status','additional_fee_amount','additional_fee_reason','additional_fee_status','rebooking_status','rebooking_original_date','rebooking_requested_date','rebooking_reason','rebooking_requested_at','rebooking_resolved_at','rebooking_resolution_note','rebooking_count']},
 FoundItem:{table:'found_items',fields:['id','created_date','updated_date','item_name','description','date_found','location_found','found_by','status','image_url','claimed_guest_name','claimed_contact','claimed_reservation_id','proof_of_ownership','released_by','date_claimed','is_active']},
 LostItemReport:{table:'lost_item_reports',fields:['id','created_date','updated_date','guest_name','reservation_number','item_lost','description','date_lost','contact_number','email','status','matched_item_id']},
 Package:{table:'packages',fields:['id','created_date','updated_date','name','description','tour_type','price','day_tour_price','night_tour_price','twenty_two_hour_price','max_guests','inclusions','gallery_images','image_url','is_active'],json:['inclusions','gallery_images'],bool:['is_active'],numeric:['price','day_tour_price','night_tour_price','twenty_two_hour_price','max_guests']},
 PaymentQrCode:{table:'payment_qr_codes',fields:['id','created_date','updated_date','label','account_name','account_number','instructions','image_url','display_order','is_active'],bool:['is_active'],numeric:['display_order']},
 ResortRule:{table:'resort_rules',fields:['id','created_date','updated_date','title','description','sort_order','is_active'],bool:['is_active'],numeric:['sort_order']},
 SiteSetting:{table:'site_settings',fields:['id','created_date','updated_date','site_name','logo_url','hero_image_url','hero_images_json','packages_banner_url','packages_banner_images_json','hero_badge_text','hero_title_line1','hero_title_line2','hero_description','body_font_style','heading_font_style','amenities_section_label','amenities_section_title','amenities_section_description','resort_gallery_json','terms_title','terms_summary','terms_content','amenities_json','require_strong_password','min_password_length','session_timeout_minutes','max_login_attempts','lockout_minutes','enable_login_notifications'],bool:['require_strong_password','enable_login_notifications'],numeric:['min_password_length','session_timeout_minutes','max_login_attempts','lockout_minutes'],json:['hero_images_json','packages_banner_images_json','resort_gallery_json','amenities_json']},
 User:{table:'users',fields:['id','created_date','updated_date','email','full_name','birth_date','phone','profile_image_url','role','disabled','is_verified','app_id','is_service','app_role'],bool:['disabled','is_verified','is_service']},
 UpcomingSchedule:{table:'upcoming_schedules',fields:['id','created_date','updated_date','title','schedule_date','start_time','end_time','location','description','created_by_name','created_by_email']},
 Review:{table:'reviews',fields:['id','created_date','updated_date','booking_id','booking_reference','guest_name','guest_email','package_name','rating','review_text','is_approved'],bool:['is_approved'],numeric:['rating']}
};
function deserialize(cfg,row){const out={...row};for(const f of cfg.json||[]){if(out[f]!==null&&out[f]!==undefined){try{out[f]=typeof out[f]==='string'?JSON.parse(out[f]):out[f];}catch{out[f]=[];}}}for(const f of cfg.bool||[])if(f in out)out[f]=!!out[f];for(const f of cfg.numeric||[])if(out[f]!==null&&out[f]!==undefined){const n=Number(out[f]);out[f]=Number.isInteger(n)?n:n;}for(const f of ['created_date','updated_date'])if(out[f] instanceof Date)out[f]=out[f].toISOString();return out;}
function serialize(cfg,f,v){if((cfg.json||[]).includes(f))return v==null?null:JSON.stringify(v);if((cfg.bool||[]).includes(f))return v?1:0;return v;}
async function validate(entity,record,exclude){if(entity==='Package'){if(!String(record.name||'').trim())throw Object.assign(new Error('Package name is required.'),{status:422});const prices=['day_tour_price','night_tour_price','twenty_two_hour_price','price'].map(x=>Number(record[x]||0));if(Math.max(...prices)<=0)throw Object.assign(new Error('Please add at least one package price.'),{status:422});if(record.is_active!==false){const [r]=await pool.query('SELECT id FROM packages WHERE LOWER(TRIM(name))=LOWER(TRIM(?)) AND is_active=1 AND id<>? LIMIT 1',[record.name,exclude||'']);if(r[0])throw Object.assign(new Error('An active package with this name already exists.'),{status:409});}}
if(entity==='Booking'){const date=String(record.booking_date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Object.assign(new Error('Booking date must be a valid date.'),{status:422});const guests=Number(record.guest_count||0);if(guests<1)throw Object.assign(new Error('Guest count must be at least 1.'),{status:422});if(record.package_id){const [p]=await pool.query('SELECT max_guests FROM packages WHERE id=? LIMIT 1',[record.package_id]);if(p[0]&&guests>Number(p[0].max_guests))throw Object.assign(new Error(`This package allows a maximum of ${p[0].max_guests} guests.`),{status:422});}const [dupe]=await pool.query(`SELECT id FROM bookings WHERE package_id=? AND booking_date=? AND id<>? AND status NOT IN ('cancelled','rejected') LIMIT 1`,[record.package_id,date,exclude||'']);if(dupe[0])throw Object.assign(new Error('This package is already booked for the selected date.'),{status:409});}
if(entity==='Review'){const rating=Number(record.rating||0);if(rating<1||rating>5)throw Object.assign(new Error('Rating must be between 1 and 5.'),{status:422});}
}
async function handler(req,res,next){try{const entity=String(req.query.entity||'');const cfg=MAP[entity];if(!cfg)return res.status(404).json({error:`Unsupported entity: ${entity}`});if(entity==='User'&&req.user?.role!=='super_admin'&&req.user?.app_role!=='super_admin')return res.status(403).json({error:'Forbidden.'});const table=cfg.table;const fields=cfg.fields;const method=req.method;
if(method==='GET'){const where=[],vals=[];let filter={};try{filter=req.query.filter?JSON.parse(req.query.filter):{};}catch{}for(const [f,v] of Object.entries(filter)){if(!fields.includes(f))continue;if(Array.isArray(v)&&v.length){where.push(`\`${f}\` IN (${v.map(()=>'?').join(',')})`);vals.push(...v.map(x=>serialize(cfg,f,x)));}else{where.push(`\`${f}\`=?`);vals.push(serialize(cfg,f,v));}}let sql=`SELECT * FROM \`${table}\``;if(where.length)sql+=' WHERE '+where.join(' AND ');const sort=String(req.query.sort||'');if(sort){const desc=sort.startsWith('-'),sf=desc?sort.slice(1):sort;if(fields.includes(sf))sql+=` ORDER BY \`${sf}\` ${desc?'DESC':'ASC'}`;}if(/^\d+$/.test(String(req.query.limit||'')))sql+=` LIMIT ${Math.min(500,Number(req.query.limit))}`;const [rows]=await pool.query(sql,vals);return res.json(rows.map(r=>deserialize(cfg,r)));}
if(method==='POST'){const p=req.body||{},n=now(),record={};for(const f of fields)if(Object.prototype.hasOwnProperty.call(p,f))record[f]=p[f];record.id=record.id||id(entity.toLowerCase());record.created_date=record.created_date||n;record.updated_date=n;if(entity==='Booking'){record.booking_reference=record.booking_reference||`KI-${cryptoRandom(4)}`;record.status=record.status||'pending';record.payment_status=record.payment_status||(record.receipt_url?'pending_verification':'unpaid');}if(entity==='Package'){record.is_active=record.is_active!==false;record.price=Number(record.price||0);record.max_guests=Number(record.max_guests||1);}if(entity==='FoundItem')record.status=record.status||'unclaimed';if(entity==='LostItemReport')record.status=record.status||'searching';await validate(entity,record);const cols=[],qs=[],vals=[];for(const f of fields)if(Object.prototype.hasOwnProperty.call(record,f)){cols.push(`\`${f}\``);qs.push('?');vals.push(serialize(cfg,f,record[f]));}await pool.query(`INSERT INTO \`${table}\` (${cols.join(',')}) VALUES (${qs.join(',')})`,vals);const [r]=await pool.query(`SELECT * FROM \`${table}\` WHERE id=? LIMIT 1`,[record.id]);return res.status(201).json(deserialize(cfg,r[0]||record));}
if(['PATCH','PUT'].includes(method)){const rid=String(req.query.id||'');if(!rid)return res.status(422).json({error:'Missing entity id.'});const [existing]=await pool.query(`SELECT * FROM \`${table}\` WHERE id=? LIMIT 1`,[rid]);if(!existing[0])return res.status(404).json({error:'Record not found.'});const record={...existing[0],...(req.body||{}),updated_date:now()};await validate(entity,record,rid);const updates=[],vals=[];for(const f of fields)if(f!=='id'&&Object.prototype.hasOwnProperty.call(req.body||{},f)){updates.push(`\`${f}\`=?`);vals.push(serialize(cfg,f,req.body[f]));}updates.push('updated_date=?');vals.push(record.updated_date,rid);await pool.query(`UPDATE \`${table}\` SET ${updates.join(',')} WHERE id=?`,vals);const [r]=await pool.query(`SELECT * FROM \`${table}\` WHERE id=? LIMIT 1`,[rid]);return res.json(deserialize(cfg,r[0]));}
if(method==='DELETE'){const rid=String(req.query.id||'');if(!rid)return res.status(422).json({error:'Missing entity id.'});await pool.query(`DELETE FROM \`${table}\` WHERE id=?`,[rid]);return res.json({success:true,id:rid});}return res.status(405).json({error:'Method not allowed.'});}catch(e){next(e);}}
function cryptoRandom(n){return require('crypto').randomBytes(n).toString('hex').toUpperCase().slice(0,8);}
router.use(auth,handler); module.exports=router;
