const express=require('express');const crypto=require('crypto');const router=express.Router();const {pool}=require('../config/database');const {auth,requireAdmin}=require('../middleware/auth');const {id,now,isAdmin}=require('../utils');const {sendMail}=require('../services/mail');
const tokenHash=t=>crypto.createHash('sha256').update(String(t).trim()).digest('hex');const preview=s=>{s=String(s||'').replace(/\s+/g,' ').trim();return s.length>180?s.slice(0,177)+'...':s;};
async function load(idv){const [r]=await pool.query(`SELECT i.*,u.full_name assigned_admin_name,u.email assigned_admin_email,(SELECT COUNT(*) FROM inquiry_messages m WHERE m.inquiry_id=i.id) message_count,(SELECT sender_type FROM inquiry_messages m WHERE m.inquiry_id=i.id ORDER BY created_date DESC,id DESC LIMIT 1) last_sender_type,(SELECT sender_name FROM inquiry_messages m WHERE m.inquiry_id=i.id ORDER BY created_date DESC,id DESC LIMIT 1) last_sender_name FROM inquiries i LEFT JOIN users u ON u.id=i.assigned_admin_id WHERE i.id=? LIMIT 1`,[idv]);return r[0]||null;}
async function messages(idv){const [r]=await pool.query('SELECT * FROM inquiry_messages WHERE inquiry_id=? ORDER BY created_date ASC,id ASC',[idv]);return r;}
function allowed(req,i,token){return isAdmin(req.user)||(req.user&&(i.user_id===req.user.id||String(i.guest_email||'').toLowerCase()===String(req.user.email||'').toLowerCase()))||(token&&i.guest_token_hash===tokenHash(token));}
router.use(auth);
router.get('/',async(req,res,next)=>{try{if(req.query.action!=='list')return res.status(405).json({error:'Unsupported inquiry action.'});if(!isAdmin(req.user))return res.status(403).json({error:'Forbidden.'});const status=String(req.query.status||'');const params=[];let sql=`SELECT i.*,u.full_name assigned_admin_name,u.email assigned_admin_email,(SELECT COUNT(*) FROM inquiry_messages m WHERE m.inquiry_id=i.id) message_count FROM inquiries i LEFT JOIN users u ON u.id=i.assigned_admin_id`;if(['open','in_progress','resolved','closed','archived'].includes(status)){sql+=' WHERE i.status=?';params.push(status);}else sql+=" WHERE i.status<>'archived'";sql+=' ORDER BY i.last_message_at DESC,i.updated_date DESC';const [r]=await pool.query(sql,params);res.json(r);}catch(e){next(e);}});
router.post('/',async(req,res,next)=>{try{const a=String(req.query.action||''),p=req.body||{};if(a==='mine'){const user=req.user;if(!user)return res.status(401).json({error:'Not authenticated.'});let sql=`SELECT i.*,u.full_name assigned_admin_name,u.email assigned_admin_email,(SELECT COUNT(*) FROM inquiry_messages m WHERE m.inquiry_id=i.id) message_count FROM inquiries i LEFT JOIN users u ON u.id=i.assigned_admin_id WHERE i.user_id=? OR LOWER(i.guest_email)=LOWER(?) ORDER BY i.last_message_at DESC`;const [r]=await pool.query(sql,[user.id,user.email]);return res.json(r);}
if(a==='create'){const name=String(p.name||p.guest_name||req.user?.full_name||'Guest').trim(),email=String(p.email||p.guest_email||req.user?.email||'').trim().toLowerCase(),subject=String(p.subject||'General Inquiry').trim(),message=String(p.message||'').trim();if(!name||!email||!message)return res.status(422).json({error:'Name, email, and message are required.'});const inquiryId=id('inquiry'),messageId=id('inquirymessage'),guestToken=crypto.randomBytes(16).toString('hex'),n=now();await pool.query('INSERT INTO inquiries (id,created_date,updated_date,guest_name,guest_email,guest_phone,subject,status,user_id,assigned_admin_id,guest_token_hash,last_message_at,last_message_preview) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[inquiryId,n,n,name,email,p.phone||null,subject,'open',req.user?.id||null,null,tokenHash(guestToken),n,preview(message)]);await pool.query('INSERT INTO inquiry_messages (id,created_date,updated_date,inquiry_id,sender_type,sender_name,sender_email,sender_user_id,message) VALUES (?,?,?,?,?,?,?,?,?)',[messageId,n,n,inquiryId,'guest',name,email,req.user?.id||null,message]);const i=await load(inquiryId);return res.status(201).json({inquiry:i,messages:await messages(inquiryId),guest_access_token:guestToken});}
if(a==='thread'){const i=await load(String(p.id||''));if(!i)return res.status(404).json({error:'Inquiry not found.'});if(!allowed(req,i,p.token))return res.status(403).json({error:'Forbidden.'});return res.json({inquiry:i,messages:await messages(i.id)});}
if(a==='reply'){const iid=String(req.query.id||p.id||''),message=String(p.message||'').trim(),i=await load(iid);if(!i)return res.status(404).json({error:'Inquiry not found.'});if(!message)return res.status(422).json({error:'Please enter a message.'});if(!allowed(req,i,p.token))return res.status(403).json({error:'Forbidden.'});if(i.status==='closed')return res.status(422).json({error:'This inquiry is already closed. Messaging is no longer available.'});const admin=isAdmin(req.user),n=now();const senderName=admin?(req.user.full_name||req.user.email):((req.user?.full_name)||i.guest_name);await pool.query('INSERT INTO inquiry_messages (id,created_date,updated_date,inquiry_id,sender_type,sender_name,sender_email,sender_user_id,message) VALUES (?,?,?,?,?,?,?,?,?)',[id('inquirymessage'),n,n,iid,admin?'admin':'guest',senderName,req.user?.email||i.guest_email,req.user?.id||null,message]);await pool.query('UPDATE inquiries SET updated_date=?,status=?,assigned_admin_id=?,last_message_at=?,last_message_preview=? WHERE id=?',[n,admin?(i.status==='resolved'?'in_progress':(i.status==='open'?'in_progress':i.status)):'open',admin?(i.assigned_admin_id||req.user.id):i.assigned_admin_id,n,preview(message),iid]);if(admin&&i.guest_email)await sendMail(i.guest_email,'Reply to your inquiry: '+i.subject,`<p>A resort admin replied:</p><blockquote>${message.replace(/</g,'&lt;')}</blockquote>`,'info').catch(()=>{});const updated=await load(iid);return res.json({inquiry:updated,messages:await messages(iid)});}
return res.status(405).json({error:'Unsupported inquiry action.'});}catch(e){next(e);}});
router.patch('/',async(req,res,next)=>{try{if(!isAdmin(req.user))return res.status(403).json({error:'Forbidden.'});const a=String(req.query.action||''),iid=String(req.query.id||''),i=await load(iid);if(!i)return res.status(404).json({error:'Inquiry not found.'});const status=a==='archive'?'archived':String(req.body?.status||'');if(!['open','in_progress','resolved','closed','archived'].includes(status))return res.status(422).json({error:'Invalid inquiry status.'});await pool.query('UPDATE inquiries SET status=?,updated_date=?,assigned_admin_id=? WHERE id=?',[status,now(),i.assigned_admin_id||req.user.id,iid]);res.json({inquiry:await load(iid),messages:await messages(iid)});}catch(e){next(e);}});
module.exports=router;
